Cleanup, consistency, tests, logic (#11)
* Fix some edge cases

* Adjust comment in test key, edit classifiers

* Adjust test case; fix state file permissions and make atomic

* Add mode option to NumericOpen, cleanup

* Tweak exception handling

* Exit on permission error

* Refactor; use Unix CSV dialect

* Simplify tests, add test

* Switch back to logging.error

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,7 @@
 name: Keygrep
-on: [push]
+on:
+  push:
+  pull_request:
 
 permissions:
   contents: read
@@ -19,8 +21,10 @@ jobs:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
-        echo "Testing if ssh-keygen is present"
-        command -V ssh-keygen
+        if ! command -v ssh-keygen; then
+          echo "ssh-keygen is required" >&2
+          exit 1
+        fi
         ssh -V
         python -m pip install --upgrade pip
         python -m pip install nox pytest
